version: '3.3'

services:
   mysql:
     image: mysql:5.5
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: cmdb
       MYSQL_USER: cmdb_user
       MYSQL_PASSWORD: cmdb_password

   php:
     depends_on:
       - mysql
     image: fauria/lap
     volumes:
       - ./:/var/www/html
     ports:
       - "8080:80"
